added unit test cases for pagination
WordPress/openverse-api pull request #1034
Opened 2022-12-07 06:20 UTC by prikshit-1103

written unit test cases for pagination class and for pagination in case of the API call

2022-12-11 08:22 UTC, dhruvkb requested changes
1. Please follow the PR message template. Not using it makes it harder to review PRs and breaks the link between the issue and the resolution.
2. Please lint the changes. The lint workflow has failed. To run lint, follow these steps.
	1. `just install`
	2. `just precommit`
	3. `just lint`
3. Please also add a test where page size is set to a non-integer value like a string or a float. You can [parametrize](https://docs.pytest.org/en/6.2.x/parametrize.html) the second test to accept all manners of invalid values.

2022-12-11 08:22 UTC, dhruvkb commented on api/test/unit/utils/test_Pagination.py
> +       class BasicPagination(pagination.PageNumberPagination):
The goal of the issue #401 was to test our `StandardPagination` class.

https://github.com/WordPress/openverse-api/blob/e3a5cfb9e7a88f8afb8167b6e6072fa5115e1e53/api/catalog/api/utils/pagination.py#L6

You should change the pagination class in your view to use `StandardPagination`.

2022-12-11 08:22 UTC, dhruvkb commented on api/test/unit/utils/test_Pagination.py
> +           'count': 502
The test is failing because the count is supposed to be 50.

2022-12-11 08:22 UTC, dhruvkb commented on api/test/unit/utils/test_Pagination.py
> +class TestPagination:
Please use a consistent indentation of 4 spaces per indent level.

2022-12-11 08:22 UTC, dhruvkb commented on api/test/unit/utils/test_Pagination.py
> + def test_setting_page_size_to_zero(self):
Test names should be a statement of expectation.

```suggestion
 def test_setting_page_size_to_zero_uses_default(self):
```

2022-12-11 08:22 UTC, dhruvkb commented on api/test/unit/utils/test_Pagination.py
> + def test_setting_page_size(self):
```suggestion
 def test_page_size_can_be_set_via_query_params(self):
```

2022-12-20 15:17 UTC, krysal commented
@prikshit-1103 I'll close this, but if you want to resume it at any time, please feel free to send another PR.

2022-12-20 15:17 UTC, closed without merging