stop tracking of .idea folder or directory
WordPress/openverse-api pull request #222
Opened 2021-09-21 07:25 UTC by PuneetDabral

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Technical details

## Tests

## Screenshots

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-09-21 07:27 UTC, PuneetDabral commented
sir check this..... now i stop tracking of .idea folder

2021-09-21 07:28 UTC, PuneetDabral commented
using this command (git rm -r --cached path_to_your_folder/)

2021-09-21 09:53 UTC, obulat requested changes

2021-09-21 09:53 UTC, obulat commented on .gitignore
> +.idea/dictionaries
The value `.idea` here was correct: it tells git to ignore all the files and folders inside `.idea` folder.
If we change it to `.idea/dictionaries`, then only `dictionaries` will be ignored, and all the other contents of `.idea` folder will be tracked by git. Please, change it back to `.idea`.

`.idea/dictionaries` directory was added to the repository before `.gitignore` was created. So, git did not remove the dictionaries, even thow they were supposed to be ignored.

2021-09-21 09:58 UTC, obulat commented
Hi, @PuneetDabral, thank you for your contribution! The removal of dictionaries from the repository works great! 🎉 

I have added a small request for change inline. Also, please, add the required PR labels on the right side (we automate the checks for one of the `aspect:` and one of the `goal:` labels) and edit the PR message filling in all the relevant items, and removing irrelevant (for example, the `Screenshots` section).

2021-09-21 17:25 UTC, PuneetDabral commented
can i again pr?

2021-09-21 17:43 UTC, PuneetDabral commented
ok sir i will update it on 12 pm

2021-09-22 12:58 UTC, PuneetDabral commented
check this sir i will update this...

2021-09-22 13:43 UTC, obulat commented
> check this sir i was already update this...

There is still a change request that needs to be addressed (regarding new lines). 

Please also edit the PR message filling in all the relevant items, including the issue that this PR fixes, checking the relevant checklist items, and removing irrelevant sections(for example, the Screenshots section).

2021-09-22 13:47 UTC, PuneetDabral commented
so now what i can change ??

2021-09-22 14:21 UTC, obulat commented
> so now what i can change ??

Click on 'Edit' in your first message:
<img width="840" alt="PRMessage" src="https://user-images.githubusercontent.com/15233243/134361234-46e00e55-0212-415c-9c5e-28d9ff4086ac.png">
And add the missing details. You can see an example of a PR message in https://github.com/WordPress/openverse-api/pull/224

Also, address this request: https://github.com/WordPress/openverse-api/pull/222/files#r713258290 . If you do not delete the extra lines, linting will fail, and we will not be able to merge the PR.

2021-09-22 14:23 UTC, PuneetDabral commented
then

2021-09-22 16:09 UTC, dhruvkb approved these changes
This should effectively stop tracking the `.idea/` directory.

2021-09-22 16:11 UTC, obulat approved these changes

2021-09-22 16:13 UTC, obulat commented
Thank you for your contribution, @PuneetDabral !

2021-09-22 16:13 UTC, merged