Removed the "cc-catalog" references from the system-architecure diagram.
WordPress/openverse-api pull request #771
Opened 2022-06-24 18:52 UTC by raghuvar-arora-au2

## Fixes
Fixes #758  by @sarayourfriend 

## Description
Recreated the diagram in draw.io, and removed the cc-catolog references. 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-06-24 18:53 UTC, raghuvar-arora-au2 commented
Where should I put the XML file and the link to the draw.io project?

2022-06-24 19:15 UTC, zackkrida commented
@raghuvar-arora-au2 how about moving all of this into a subdirectory of the `readme_assets` folder, maybe something like:

```
readme_assets
└── system_diagram
    ├── diagram.png
    ├── diagram.xml
    └── readme.md
```

and then the link to draw.io could go in that readme file? if you do it this way, make sure to update path to the image in the repo README file. 

The diagram looks excellent! Thanks for this.

2022-06-24 21:10 UTC, raghuvar-arora-au2 commented
Made the changes, thanks

2022-06-25 10:29 UTC, sarayourfriend reviewed
This is great @raghuvar-arora-au2! It looks like you'll need to run `just lint` at the root of the repository and commit the changes to the markdown file, but otherwise this is great to see :slightly_smiling_face: 

I left a couple things that would be nice to update while we're making this change as well.

Additionally, I don't think the `shares.cc` service is running anymore, but maybe @zackkrida could confirm that. We might want to remove that block as well.

Thanks again for the contribution!!

2022-06-25 10:29 UTC, sarayourfriend commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-59" value="-Site cache&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;nbsp;&lt;br&gt;-Traffic stats&amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;nbsp;&lt;br&gt;-Dead l
We no longer hold traffic stats anywhere as far as I am aware, so I think we can remove that bit.

```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-59" value="-Site cache&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;nbsp;&lt;br&gt;-Dead link cache" style="text;html=1;align=left;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;" vertex="1" parent="1">
```

2022-06-25 10:29 UTC, sarayourfriend commented on readme_assets/system_diagram/system_architecture.xml
> +        </mxCell>
I think 'django-api' might be a better term to use here as "catalog" could be easily confused with our https://github.com/wordpress/openverse-catalog project.

```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-12" value="django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" vertex="1" parent="1">
          <mxGeometry x="455" y="480" width="80" height="40" as="geometry" />
        </mxCell>
        <mxCell id="JVIGxF9oKAkimninJbSp-13" value="django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" vertex="1" parent="1">
          <mxGeometry x="545" y="480" width="80" height="40" as="geometry" />
        </mxCell>
        <mxCell id="JVIGxF9oKAkimninJbSp-14" value="django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" vertex="1" parent="1">
          <mxGeometry x="635" y="480" width="80" height="40" as="geometry" />
        </mxCell>
```

2022-06-27 11:37 UTC, obulat requested changes
Thank you for amazing work, @raghuvar-arora-au2 !

There are a couple of things that we don't have anymore, could you please remove them. I've scratched them out in the screenshot below:
<img width="636" alt="Screen Shot 2022-06-27 at 2 34 04 PM" src="https://user-images.githubusercontent.com/15233243/175932522-7205d008-e6ca-4db1-af75-3b27cfb88cdf.png">

2022-06-27 16:02 UTC, stacimc commented
This is looking great! 🎉 

Can we update the text "Ingest" here to say "Data refresh"? Context in [comment](https://github.com/WordPress/openverse-api/issues/758#issuecomment-1167534569). (I do think it's correct to keep the phrase "Ingestion server", since the server is currently named that).

<img width="636" alt="Screen Shot 2022-06-27 at 2 34 04 PM" src="https://user-images.githubusercontent.com/28990489/175576168-ec7fb322-5a15-42f7-af8c-3ff827b3024f.png">

2022-06-28 04:10 UTC, dhruvkb approved these changes
I'm not sure if we should be including the frontend in the diagram that's in the API repo, but it's not wrong so not a problem.

One technical error in the "API Database" ↔ "API Server Group" link is that we no longer have link shortening data and lists. Those tables exist but that functionality has been deactivated.

Also a couple of grammatical improvements:
- "Django-api" &rarr; "Django API"
- "frontend" &rarr; "Frontend"

2022-06-28 08:08 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-12" value="Django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-12" value="Django API" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```

2022-06-28 08:08 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-13" value="Django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-13" value="Django API" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```

2022-06-28 08:09 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-14" value="Django-api" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-14" value="Django API" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
```

2022-06-28 08:09 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-16" value="frontend" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#f8cecc;strokeColor=#b85450;" parent="1" vertex="1">
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-16" value="Frontend" style="rounded=0;whiteSpace=wrap;html=1;strokeWidth=1;fillColor=#f8cecc;strokeColor=#b85450;" parent="1" vertex="1">
```

2022-06-28 08:10 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-65" value="External dependancy" style="shape=partialRectangle;html=1;whiteSpace=wrap;connectable=0;fillColor=#f8cecc;top=0;left=0;bottom=0;right=0;overflow=hi
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-65" value="External dependency" style="shape=partialRectangle;html=1;whiteSpace=wrap;connectable=0;fillColor=#f8cecc;top=0;left=0;bottom=0;right=0;overflow=hidden;pointerEvents=1;align=left;spacingLeft=10;strokeWidth=1;strokeColor=#b85450;" parent="JVIGxF9oKAkimninJbSp-62" vertex="1">
```

2022-06-28 08:11 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-60" value="-Detail views&lt;br&gt;-Lists&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;br&gt;-Content provider data&lt;br&gt;&lt;div sty
```suggestion
        <mxCell id="JVIGxF9oKAkimninJbSp-60" value="-Detail views&lt;br&gt;-Lists&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;br&gt;-Content provider data&lt;br&gt;&lt;div style=&quot;&quot;&gt;&lt;span style=&quot;background-color: initial;&quot;&gt;&lt;/span&gt;&lt;/div&gt;" style="text;html=1;align=left;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;" parent="1" vertex="1">
```

2022-06-28 08:12 UTC, obulat commented on readme_assets/system_diagram/system_architecture.xml
> +        <mxCell id="JVIGxF9oKAkimninJbSp-60" value="-Detail views&lt;br&gt;-Lists&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;br&gt;-Content provider data&lt;br&gt;&lt;div sty
I'm not sure that this suggestion will work for PNG generation, but we should remove the `Link shortening data` here, too.

2022-07-03 07:26 UTC, obulat approved these changes
Thank you for your contribution, @raghuvar-arora-au2 ! The diagram looks great 🎉

2022-07-03 07:26 UTC, merged

2022-07-11 20:15 UTC, AetherUnbound commented
Just dropping in to say thanks so much for this contribution @raghuvar-arora-au2! This is excellent 🥳